colors; output

diff --git a/usr/lib/first_run_initializer_gui b/usr/lib/first_run_initializer_gui
--- a/usr/lib/first_run_initializer_gui
+++ b/usr/lib/first_run_initializer_gui
@@ -9,6 +9,52 @@
 
 #set -x
 
+colors() {
+   ## Thanks to:
+   ## http://mywiki.wooledge.org/BashFAQ/037
+   ## Variables for terminal requests.
+   [[ -t 2 ]] && {
+       alt=$(      tput smcup  || tput ti      ) # Start alt display
+       ealt=$(     tput rmcup  || tput te      ) # End   alt display
+       hide=$(     tput civis  || tput vi      ) # Hide cursor
+       show=$(     tput cnorm  || tput ve      ) # Show cursor
+       save=$(     tput sc                     ) # Save cursor
+       load=$(     tput rc                     ) # Load cursor
+       bold=$(     tput bold   || tput md      ) # Start bold
+       stout=$(    tput smso   || tput so      ) # Start stand-out
+       estout=$(   tput rmso   || tput se      ) # End stand-out
+       under=$(    tput smul   || tput us      ) # Start underline
+       eunder=$(   tput rmul   || tput ue      ) # End   underline
+       reset=$(    tput sgr0   || tput me      ) # Reset cursor
+       blink=$(    tput blink  || tput mb      ) # Start blinking
+       italic=$(   tput sitm   || tput ZH      ) # Start italic
+       eitalic=$(  tput ritm   || tput ZR      ) # End   italic
+   [[ $TERM != *-m ]] && {
+       red=$(      tput setaf 1|| tput AF 1    )
+       green=$(    tput setaf 2|| tput AF 2    )
+       yellow=$(   tput setaf 3|| tput AF 3    )
+       blue=$(     tput setaf 4|| tput AF 4    )
+       magenta=$(  tput setaf 5|| tput AF 5    )
+       cyan=$(     tput setaf 6|| tput AF 6    )
+   }
+       white=$(    tput setaf 7|| tput AF 7    )
+       default=$(  tput op                     )
+       eed=$(      tput ed     || tput cd      )   # Erase to end of display
+       eel=$(      tput el     || tput ce      )   # Erase to end of line
+       ebl=$(      tput el1    || tput cb      )   # Erase to beginning of line
+       ewl=$eel$ebl                                # Erase whole line
+       draw=$(     tput -S <<< '   enacs
+                                   smacs
+                                   acsc
+                                   rmacs' || { \
+                   tput eA; tput as;
+                   tput ac; tput ae;         } )   # Drawing characters
+       back=$'\b'
+   } 2>/dev/null ||:
+}
+
+colors
+
 fake_progress_bar() {
    while true; do
       ps -p $sleeppid_one $sleeppid_two $sleeppid_three $sleeppid_four $first_run_initializer_pid >/dev/null 2>&1
@@ -41,9 +87,9 @@ touch "$start_file"
 sync
 
 echo "\
-[INFO] [Whonix First Run Initializer]: Preparing Whonix... Will reboot
-       when finished... Do not interrupt this process or your system might be
-       unstable! This may take a while..."
+[${cyan}${bold}INFO${reset}] [${cyan}Whonix First Run Initializer${reset}]: Preparing Whonix... Will reboot
+       when finished... ${under}Do not interrupt this process or your system might be${reset}
+       ${under}unstable!${reset} This may take a while..."
 
 ## The sleep is just in for the look an feel.
 sleep 10 &
@@ -61,12 +107,13 @@ touch "$done_file"
 sync
 
 if [ "$first_run_initializer_exit_code" = "0" ]; then
-   echo "[INFO] [Whonix First Run Initializer]: Done. Rebooting..."
+   echo "[${cyan}${bold}INFO${reset}] [${cyan}Whonix First Run Initializer${reset}]: Done. Rebooting... This may take a while..."
 else
    echo "\
-[ERROR] [Whonix First Run Initializer]: Error!
-        Please report this Whonix bug! Submit Whonix First Run Initializer's
-        log file $log_file to Whonix developers! Rebooting..."
+[${red}${bold}ERROR${reset}] [${cyan}Whonix First Run Initializer${reset}]: Error!
+        ${under}Please report this Whonix bug! Submit Whonix First Run Initializer's${reset}
+        ${under}log file $log_file to Whonix developers!${reset}
+        Rebooting... This may take a while..."
 fi
 
 ## The sleep is just in for the look an feel.
@@ -80,7 +127,7 @@ if [ "$CI" = "true" ]; then
    ## Otherwise you'll run into...
    ## "I'm sorry but there was an error with the connection to the VM.
    ## Your job will be requeued shortly."
-   echo "[INFO] [Whonix First Run Initializer]: CI detected. Skipping reboot."
+   echo "[${cyan}${bold}INFO${reset}] [${cyan}Whonix First Run Initializer${reset}]: CI detected. Skipping reboot."
 else
    reboot
 fi
@@ -90,7 +137,7 @@ sleep 60 &
 sleeppid_three="$!"
 fake_progress_bar
 
-echo "[ERROR] [Whonix First Run Initializer]: Rebooting not done after 60 seconds. Please report this Whonix bug!"
+echo "[${red}${bold}ERROR${reset}] [${cyan}Whonix First Run Initializer${reset}]: Rebooting not done after 60 seconds. Please report this Whonix bug!"
 
 ## Sleep, so this message has a chance of being read.
 sleep 10 &
