root check

diff --git a/usr/lib/first_run_initializer_gui b/usr/lib/first_run_initializer_gui
--- a/usr/lib/first_run_initializer_gui
+++ b/usr/lib/first_run_initializer_gui
@@ -9,6 +9,13 @@
 
 #set -x
 
+if [ "$(id -u)" != "0" ]; then
+    echo "ERROR: This must be run as root (sudo)!"
+    exit 1
+else
+    true "INFO: Script running as root."
+fi
+
 colors() {
    ## Thanks to:
    ## http://mywiki.wooledge.org/BashFAQ/037
